### ISSUE TITLE
Ideas for New User Onboarding

### ISSUE THREAD

**Issue by andyl** [elixir-tools/tableau_new#18]
Coming back to Tableau after a few months, here are some ideas for the generator.  The basic idea is to streamline new-user onboarding when they generate a new site.

1. Generate working examples of Tableau features: `_posts`, `_pages`, `_data`, RSS, etc.  under the theory that it's easier to delete functionality from a scaffold than add it to a blank-slate.
2. The generated pages should have light documentation (written in markdown) on how to customize and extend the new site.
3. Include a simple sidebar layout (maybe for documentation) 
4. Include function-components for generating menus and menu links.

Probably would be nice to have a basic styling - that's not my forte.

Just putting this out there for feedback.  If this is interesting I can start to submit PRs and/or collaborate with others.  WDYT?

**Comment by mhanberg** [comment]
Sounds great to me!

**Comment by andyl** [comment]
OK good I'll put this on my TODO list.  May take a month or two to find time to finish this - will report back here when I have something to share.

**Comment by andyl** [comment]
I'm gonna close this, and will post another idea that I think is better.
